# This is a basic workflow to help you get started with Actions

name: Liquibase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "release/*" ]
  pull_request:
    branches: [ "release/*" ]

  # Allows you to raaaun this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  marcacao-liquibase-action:
    runs-on: ubuntu-latest
    name: LiquibasePontoEletronico
    steps:
      - run: echo ${{ github.workspace }}

      - uses: actions/checkout@v4
      - uses: liquibase-github-actions/update@v4.26.0
      
        with:
          searchPath: ${{ github.workspace }}
          driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
          changeLogFile: ${{ github.workspace }}/changelogs/202403211414_createMarcacao.sql
          defaultSchemaName: "dbo"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: '${{ secrets.URL }}'      
 